export const ACTION_TYPE = {
    SET_AUTHORIZED_USER: 'SET_AUTHORIZED_USER',
    REMOVE_AUTHORIZED_USER: 'REMOVE_AUTHORIZED_USER',

    SET_WORKOUTS: 'SET_WORKOUTS',

    SET_WORKOUT: 'SET_WORKOUT',
    REMOVE_WORKOUT: 'REMOVE_WORKOUT',
    UPDATE_WORKOUT: 'UPDATE_WORKOUT',
    CREATE_WORKOUT: 'CREATE_WORKOUT',

    SET_USERS: 'SET_USERS',
    REMOVE_USER: 'REMOVE_USER',
    UPDATE_USER: 'UPDATE_USER',
} as const;

export type ActionType = (typeof ACTION_TYPE)[keyof typeof ACTION_TYPE];
